sonar.projectKey=sergr88_python-project-52
sonar.organization=sergr88

sonar.sources=task_manager
sonar.exclusions=**/migrations/**,**/tests.py,**/__pycache__/**

sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml
