# Generated by Django 6.0.2 on 2026-03-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '__first__'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, to='labels.label', verbose_name='Labels'),
        ),
    ]
