# Generated by Django 6.0.2 on 2026-03-01 17:30

from django.db import migrations

DEFAULT_STATUS_NAMES = ['New', 'In progress', 'Testing', 'Done']


def create_default_statuses(apps, schema_editor):
    """Create default task statuses."""
    Status = apps.get_model('statuses', 'Status')
    for name in DEFAULT_STATUS_NAMES:
        Status.objects.get_or_create(name=name)


def remove_default_statuses(apps, schema_editor):
    """Remove default task statuses."""
    Status = apps.get_model('statuses', 'Status')
    Status.objects.filter(name__in=DEFAULT_STATUS_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_status_name'),
    ]

    operations = [
        migrations.RunPython(
            create_default_statuses,
            remove_default_statuses,
        ),
    ]
