# Generated by Django 6.0.2 on 2026-03-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_populate_default_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Task status'},
        ),
    ]
